# Secure Docker Compose configuration for ATM System
version: '3.8'

services:
  atm-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: atm-system-secure
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    # Security configurations
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE  # Only if binding to privileged ports
    read_only: true
    tmpfs:
      - /tmp:rw,size=100M,mode=1777
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Restart policy
    restart: unless-stopped
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Network security
    networks:
      - atm-network

networks:
  atm-network:
    driver: bridge
    # Enable network isolation
    internal: false  # Set to true for internal-only access
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

# Volumes (if needed for logs or data)
volumes:
  atm-logs:
    driver: local
